### ISSUE TITLE
Add command line tools for math

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-math#198]
## Desired behavior

Ignition math has a lot of handy APIs, but they can only be used by writing a C++ program. It would be nice to expose some of these as a handy command line tool. Some nice tools to offer:

* Convert degrees :arrows_counterclockwise:  radians
* Convert euler angles :arrows_counterclockwise: quaternions
* Get the moments of inertia for a shape given its dimensions and mass

## Alternatives considered

GUI tools could also be handy. What I currently do for the use cases above is opening a website that does it for me, or opening a calculator, or doing it by hand...

## Implementation suggestion

Use [ign-tools](https://github.com/ignitionrobotics/ign-tools/), see an example on [ign-transport](https://github.com/ignitionrobotics/ign-transport/tree/ign-transport9/src/cmd).

Commands could look like this:

`ign math --quaternion_to_euler "0 0 0 1"`

**Comment by NickNair** [comment]
Is this issue closed?

**Comment by scpeters** [comment]
> * Convert euler angles 🔄 quaternions

> Commands could look like this:
> 
> `ign math --quaternion_to_euler "0 0 0 1"`

we have examples for converting between Euler angles and quaternions:

* https://github.com/ignitionrobotics/ign-math/blob/ign-math6/examples/quaternion_from_euler.cc
* https://github.com/ignitionrobotics/ign-math/blob/ign-math6/examples/quaternion_to_euler.cc

we could use that as a reference when implementing this

**Comment by NickNair** [comment]
Why do I get this error when I run the ruby file in examples ?
```
Traceback (most recent call last):
	2: from angle_example.rb:23:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ignition/math (LoadError)

```

**Comment by chapulina** [comment]
> Why do I get this error when I run the ruby file in examples ?

@NickNair , please direct questions to http://answers.gazebosim.org. If you believe you found a bug, please ticket a new issue filling the template and explaining how to reproduce your problem.

**Comment by NickNair** [comment]
I'm sorry for posting this here but. Could you tell me how to compile and install the ruby interface library

**Comment by sdhar04** [comment]
@chapulina I would like to work on this issue. Could you tell me which files I need to change in order to implement this?
